# Generated by Django 2.2.10 on 2020-02-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('Url', models.CharField(max_length=20)),
                ('Processor', models.CharField(max_length=20)),
                ('Ram', models.CharField(max_length=20)),
                ('Display', models.CharField(max_length=20)),
                ('OS', models.CharField(max_length=20)),
                ('Battery', models.CharField(max_length=20)),
                ('Image1', models.CharField(max_length=20)),
                ('Image2', models.CharField(max_length=20)),
                ('Image3', models.CharField(max_length=20)),
            ],
        ),
    ]
