# Generated by Django 2.2.10 on 2020-02-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='Battery',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='phones',
            name='Display',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='phones',
            name='Image1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='phones',
            name='Image2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='phones',
            name='Image3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='phones',
            name='OS',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='phones',
            name='Processor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='phones',
            name='Ram',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='phones',
            name='Url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='phones',
            name='brand',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='phones',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
